// frontend-react/src/components/sidebar/ProjectList.tsx
import { useRef, useState } from "react";
import {
  DndContext,
  DragOverlay,
  closestCenter,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
  type DragStartEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import {
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
} from "@/components/ui/sidebar";
import { useProjectStore } from "@/lib/stores/projects";
import { useWorktreeStore } from "@/lib/stores/worktrees";
import type { Worktree } from "@/lib/types";
import type { SidebarDialogState } from "./types";
import { ProjectItem } from "./ProjectItem";

interface ProjectListProps {
  setDialogState: React.Dispatch<React.SetStateAction<SidebarDialogState>>;
}

export function ProjectList({ setDialogState }: ProjectListProps) {
  const projects = useProjectStore((s) => s.projects);
  const isExpanded = useProjectStore((s) => s.isExpanded);
  const toggleExpanded = useProjectStore((s) => s.toggleExpanded);
  const reorderProjects = useProjectStore((s) => s.reorder);

  const selectedWorktreeId = useWorktreeStore((s) => s.selectedWorktreeId);
  const worktreesForProject = useWorktreeStore((s) => s.worktreesForProject);
  const selectWorktree = useWorktreeStore((s) => s.select);
  const projectError = useWorktreeStore((s) => s.projectError);
  const reorderWorktrees = useWorktreeStore((s) => s.reorder);

  const [isDragging, setIsDragging] = useState(false);
  const dragSnapshotRef = useRef<{
    html: string;
    width: number;
  } | null>(null);
  const [, forceRender] = useState(0);

  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: { distance: 5 },
    }),
  );

  function handleDragStart(event: DragStartEvent) {
    setIsDragging(true);

    // Clone the actual DOM element for a pixel-perfect overlay.
    const el = document.querySelector(
      `[data-project-drag-item="true"][data-project-id="${event.active.id}"]`,
    );
    if (el instanceof HTMLElement) {
      dragSnapshotRef.current = {
        html: el.innerHTML,
        width: el.getBoundingClientRect().width,
      };
    }
    forceRender((n) => n + 1);
  }

  function handleDragEnd(event: DragEndEvent) {
    setIsDragging(false);
    dragSnapshotRef.current = null;
    const { active, over } = event;
    if (!over || active.id === over.id) return;

    const oldIndex = projects.findIndex((p) => p.id === active.id);
    const newIndex = projects.findIndex((p) => p.id === over.id);
    if (oldIndex === -1 || newIndex === -1) return;

    const reordered = [...projects];
    const [moved] = reordered.splice(oldIndex, 1);
    reordered.splice(newIndex, 0, moved);

    reorderProjects(reordered.map((p) => p.id));
  }

  function localWorktree(projectId: string): Worktree | null {
    return worktreesForProject(projectId).find((wt) => wt.is_local) ?? null;
  }

  return (
    <SidebarGroup>
      <SidebarGroupContent>
        <SidebarMenu>
          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            onDragStart={handleDragStart}
            onDragEnd={handleDragEnd}
            onDragCancel={() => {
              setIsDragging(false);
              dragSnapshotRef.current = null;
            }}
          >
            <SortableContext
              items={projects.map((p) => p.id)}
              strategy={verticalListSortingStrategy}
            >
              <div
                className="flex w-full min-w-0 cursor-default select-none flex-col gap-1 overflow-x-hidden"
                data-sidebar-dragging={isDragging || undefined}
              >
                {projects.map((project) => (
                  <ProjectItem
                    key={project.id}
                    project={project}
                    isExpanded={isExpanded(project.id)}
                    selectedWorktreeId={selectedWorktreeId}
                    localWorktree={localWorktree(project.id)}
                    worktrees={worktreesForProject(project.id)}
                    projectError={projectError(project.id)}
                    onToggleExpand={() => toggleExpanded(project.id)}
                    onRequestRename={() => {
                      setDialogState((s) => ({
                        ...s,
                        actionError: null,
                        renameProject: {
                          projectId: project.id,
                          currentName: project.name,
                        },
                      }));
                    }}
                    onRequestRemove={() => {
                      setDialogState((s) => ({
                        ...s,
                        actionError: null,
                        confirmRemoveProject: project.id,
                      }));
                    }}
                    onRequestAddWorktree={() => {
                      setDialogState((s) => ({
                        ...s,
                        actionError: null,
                        addWorktree: {
                          projectId: project.id,
                          projectName: project.name,
                        },
                      }));
                    }}
                    onSelectWorktree={selectWorktree}
                    onRequestRemoveWorktree={(projectId, worktree) => {
                      setDialogState((s) => ({
                        ...s,
                        actionError: null,
                        confirmRemoveWorktree: {
                          projectId,
                          worktree,
                        },
                      }));
                    }}
                    onWorktreeReorder={reorderWorktrees}
                    listDragging={isDragging}
                  />
                ))}
              </div>
            </SortableContext>
            <DragOverlay>
              {dragSnapshotRef.current && (
                <div
                  className="group/menu-item relative rounded-md opacity-50"
                  style={{
                    width: dragSnapshotRef.current.width,
                  }}
                  dangerouslySetInnerHTML={{
                    __html: dragSnapshotRef.current.html,
                  }}
                />
              )}
            </DragOverlay>
          </DndContext>
        </SidebarMenu>
      </SidebarGroupContent>
    </SidebarGroup>
  );
}

// frontend/src/lib/components/sidebar/ProjectList.svelte
<script lang="ts">
  import * as Sidebar from "$lib/components/ui/sidebar/index.js";
  import { flip } from "svelte/animate";
  import { dragHandleZone } from "svelte-dnd-action";
  import type { Project, Worktree } from "$lib/types";
  import type {
    DndProject,
    ProjectStore,
    SidebarDialogState,
    WorktreeStore,
  } from "./types.js";
  import ProjectItem from "./ProjectItem.svelte";

  let {
    projectStore,
    worktreeStore,
    dialogState,
  }: {
    projectStore: ProjectStore;
    worktreeStore: WorktreeStore;
    dialogState: SidebarDialogState;
  } = $props();

  const FLIP_MS = 150;

  let draggingProjects = $state(false);
  let draggingWorktrees = $state(false);
  let isDragging = $derived(draggingProjects || draggingWorktrees);

  let dndProjects = $state<DndProject[]>([]);

  $effect(() => {
    if (!draggingProjects) {
      dndProjects = projectStore.projects.map((p: Project) => ({ ...p }));
    }
  });

  function handleConsider(e: CustomEvent<{ items: DndProject[] }>) {
    draggingProjects = true;
    dndProjects = e.detail.items;
  }

  function handleFinalize(e: CustomEvent<{ items: DndProject[] }>) {
    dndProjects = e.detail.items;
    draggingProjects = false;
    projectStore.reorder(dndProjects.map((p) => p.id));
  }

  function localWorktree(projectId: string): Worktree | null {
    return (
      worktreeStore
        .worktreesForProject(projectId)
        .find((wt: Worktree) => wt.is_local) ?? null
    );
  }
</script>

<Sidebar.Group>
  <Sidebar.GroupContent>
    <Sidebar.Menu>
      <div
        class="flex w-full min-w-0 flex-col gap-1"
        data-sidebar-dragging={isDragging || undefined}
        use:dragHandleZone={{
          items: dndProjects,
          flipDurationMs: FLIP_MS,
          type: "projects",
          dropTargetStyle: {},
          centreDraggedOnCursor: false,
          useCursorForDetection: true,
          morphDisabled: true,
        }}
        onconsider={handleConsider}
        onfinalize={handleFinalize}
      >
        {#each dndProjects as project (project.id)}
          <div
            animate:flip={{
              duration: draggingProjects ? FLIP_MS : 0,
            }}
            class="group/menu-item relative rounded-md"
            data-project-drag-item="true"
          >
            <ProjectItem
              {project}
              isExpanded={projectStore.isExpanded(project.id)}
              selectedWorktreeId={worktreeStore.selectedWorktreeId}
              localWorktree={localWorktree(project.id)}
              worktrees={worktreeStore.worktreesForProject(project.id)}
              projectError={worktreeStore.projectError(project.id)}
              onToggleExpand={() => projectStore.toggleExpanded(project.id)}
              onRequestRename={() => {
                dialogState.actionError = null;
                dialogState.renameProject = {
                  projectId: project.id,
                  currentName: project.name,
                };
              }}
              onRequestRemove={() => {
                dialogState.actionError = null;
                dialogState.confirmRemoveProject = project.id;
              }}
              onRequestAddWorktree={() => {
                dialogState.actionError = null;
                dialogState.addWorktree = {
                  projectId: project.id,
                  projectName: project.name,
                };
              }}
              onSelectWorktree={(id) => worktreeStore.select(id)}
              onRequestRemoveWorktree={(projectId, worktree) => {
                dialogState.actionError = null;
                dialogState.confirmRemoveWorktree = {
                  projectId,
                  worktree,
                };
              }}
              onWorktreeDraggingChange={(d) => {
                draggingWorktrees = d;
              }}
              onWorktreeReorder={(projectId, ids) =>
                worktreeStore.reorder(projectId, ids)}
            />
          </div>
        {/each}
      </div>
    </Sidebar.Menu>
  </Sidebar.GroupContent>
</Sidebar.Group>
