// frontend/src/lib/components/SidebarResizeHandle.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { useSidebar } from "$lib/components/ui/sidebar/index.js";
  import { getSidebarWidthStore } from "$lib/stores/sidebarWidth.svelte";

  type ResizeState = {
    pointerId: number;
    startX: number;
    startWidth: number;
  };

  const KEYBOARD_RESIZE_STEP = 16;

  const sidebar = useSidebar();
  const sidebarWidthStore = getSidebarWidthStore();

  let resizeState = $state<ResizeState | null>(null);
  let pendingClientX = $state<number | null>(null);
  let resizeRafId: number | null = null;

  function clearQueuedResize(): void {
    if (resizeRafId != null) {
      cancelAnimationFrame(resizeRafId);
      resizeRafId = null;
    }
    pendingClientX = null;
  }

  function applyResize(clientX: number): void {
    if (!resizeState) {
      return;
    }

    const delta = clientX - resizeState.startX;
    sidebarWidthStore.setWidth(resizeState.startWidth + delta);
  }

  function flushQueuedResize(): void {
    resizeRafId = null;
    if (pendingClientX == null) {
      return;
    }
    applyResize(pendingClientX);
    pendingClientX = null;
  }

  function queueResize(clientX: number): void {
    pendingClientX = clientX;
    if (resizeRafId != null) {
      return;
    }
    resizeRafId = requestAnimationFrame(flushQueuedResize);
  }

  function handlePointerDown(e: PointerEvent): void {
    if (e.button !== 0 || sidebar.isMobile) {
      return;
    }

    resizeState = {
      pointerId: e.pointerId,
      startX: e.clientX,
      startWidth: sidebarWidthStore.width,
    };

    sidebarWidthStore.setResizing(true);

    const handle = e.currentTarget as HTMLElement | null;
    handle?.setPointerCapture(e.pointerId);
    clearQueuedResize();
    e.preventDefault();
  }

  function handlePointerMove(e: PointerEvent): void {
    if (!resizeState || e.pointerId !== resizeState.pointerId) {
      return;
    }

    queueResize(e.clientX);
  }

  function handlePointerEnd(e: PointerEvent): void {
    if (!resizeState || e.pointerId !== resizeState.pointerId) {
      return;
    }

    const handle = e.currentTarget as HTMLElement | null;
    if (handle?.hasPointerCapture(e.pointerId)) {
      handle.releasePointerCapture(e.pointerId);
    }
    clearQueuedResize();
    applyResize(e.clientX);
    resizeState = null;
    sidebarWidthStore.setResizing(false);
    sidebarWidthStore.flushPendingPersist();
  }

  function handleKeydown(e: KeyboardEvent): void {
    if (sidebar.isMobile) {
      return;
    }

    if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") {
      return;
    }

    e.preventDefault();
    const delta =
      e.key === "ArrowRight" ? KEYBOARD_RESIZE_STEP : -KEYBOARD_RESIZE_STEP;
    sidebarWidthStore.setWidth(sidebarWidthStore.width + delta);
  }

  onDestroy(() => {
    clearQueuedResize();
    sidebarWidthStore.setResizing(false);
    sidebarWidthStore.flushPendingPersist();
  });
</script>

<button
  type="button"
  aria-label="Resize sidebar"
  class="fixed inset-y-0 left-[calc(var(--sidebar-width)-4px)]
    z-30 hidden w-2 cursor-e-resize touch-none bg-transparent
    p-0 transition-[left,opacity] duration-200 ease-linear
    md:block
    peer-data-[state=collapsed]:-left-10
    peer-data-[state=collapsed]:pointer-events-none
    peer-data-[state=collapsed]:opacity-0
    after:absolute after:inset-y-0 after:left-1/2
    after:w-[2px] after:-translate-x-1/2
    hover:after:bg-sidebar-border
    focus-visible:after:bg-sidebar-border"
  class:!transition-none={sidebarWidthStore.isResizing}
  onpointerdown={handlePointerDown}
  onpointermove={handlePointerMove}
  onpointerup={handlePointerEnd}
  onpointercancel={handlePointerEnd}
  onlostpointercapture={handlePointerEnd}
  onkeydown={handleKeydown}
></button>

// frontend-react/src/components/SidebarResizeHandle.tsx
import { useCallback, useEffect, useRef } from "react";
import { useSidebar } from "@/components/ui/sidebar";
import { useSidebarWidthStore } from "@/lib/stores/sidebarWidth";
import { cn } from "@/lib/utils";

const KEYBOARD_RESIZE_STEP = 16;

type ResizeState = {
  pointerId: number;
  startX: number;
  startWidth: number;
};

export function SidebarResizeHandle() {
  const { isMobile } = useSidebar();
  const width = useSidebarWidthStore((s) => s.width);
  const isResizing = useSidebarWidthStore((s) => s.isResizing);
  const setWidth = useSidebarWidthStore((s) => s.setWidth);
  const setResizing = useSidebarWidthStore((s) => s.setResizing);
  const flushPendingPersist = useSidebarWidthStore(
    (s) => s.flushPendingPersist,
  );

  const resizeStateRef = useRef<ResizeState | null>(null);
  const pendingClientXRef = useRef<number | null>(null);
  const resizeRafIdRef = useRef<number | null>(null);

  const clearQueuedResize = useCallback(() => {
    if (resizeRafIdRef.current != null) {
      cancelAnimationFrame(resizeRafIdRef.current);
      resizeRafIdRef.current = null;
    }
    pendingClientXRef.current = null;
  }, []);

  const applyResize = useCallback(
    (clientX: number) => {
      const rs = resizeStateRef.current;
      if (!rs) return;
      const delta = clientX - rs.startX;
      setWidth(rs.startWidth + delta);
    },
    [setWidth],
  );

  const flushQueuedResize = useCallback(() => {
    resizeRafIdRef.current = null;
    if (pendingClientXRef.current == null) return;
    applyResize(pendingClientXRef.current);
    pendingClientXRef.current = null;
  }, [applyResize]);

  const queueResize = useCallback(
    (clientX: number) => {
      pendingClientXRef.current = clientX;
      if (resizeRafIdRef.current != null) return;
      resizeRafIdRef.current = requestAnimationFrame(flushQueuedResize);
    },
    [flushQueuedResize],
  );

  useEffect(() => {
    return () => {
      clearQueuedResize();
      setResizing(false);
      flushPendingPersist();
    };
  }, [clearQueuedResize, setResizing, flushPendingPersist]);

  const handlePointerDown = useCallback(
    (e: React.PointerEvent) => {
      if (e.button !== 0 || isMobile) return;

      resizeStateRef.current = {
        pointerId: e.pointerId,
        startX: e.clientX,
        startWidth: width,
      };
      setResizing(true);

      const handle = e.currentTarget as HTMLElement;
      handle.setPointerCapture(e.pointerId);
      clearQueuedResize();
      e.preventDefault();
    },
    [isMobile, width, setResizing, clearQueuedResize],
  );

  const handlePointerMove = useCallback(
    (e: React.PointerEvent) => {
      const rs = resizeStateRef.current;
      if (!rs || e.pointerId !== rs.pointerId) return;
      queueResize(e.clientX);
    },
    [queueResize],
  );

  const handlePointerEnd = useCallback(
    (e: React.PointerEvent) => {
      const rs = resizeStateRef.current;
      if (!rs || e.pointerId !== rs.pointerId) return;

      const handle = e.currentTarget as HTMLElement;
      if (handle.hasPointerCapture(e.pointerId)) {
        handle.releasePointerCapture(e.pointerId);
      }
      clearQueuedResize();
      applyResize(e.clientX);
      resizeStateRef.current = null;
      setResizing(false);
      flushPendingPersist();
    },
    [clearQueuedResize, applyResize, setResizing, flushPendingPersist],
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (isMobile) return;
      if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") {
        return;
      }
      e.preventDefault();
      const delta =
        e.key === "ArrowRight" ? KEYBOARD_RESIZE_STEP : -KEYBOARD_RESIZE_STEP;
      setWidth(width + delta);
    },
    [isMobile, width, setWidth],
  );

  return (
    <button
      type="button"
      aria-label="Resize sidebar"
      className={cn(
        "fixed inset-y-0 left-[calc(var(--sidebar-width)-4px)]",
        "z-30 hidden w-2 cursor-e-resize touch-none",
        "bg-transparent p-0 transition-[left,opacity]",
        "duration-200 ease-linear md:block",
        "peer-data-[state=collapsed]:-left-10",
        "peer-data-[state=collapsed]:pointer-events-none",
        "peer-data-[state=collapsed]:opacity-0",
        "after:absolute after:inset-y-0 after:left-1/2",
        "after:w-[2px] after:-translate-x-1/2",
        "hover:after:bg-sidebar-border",
        "focus-visible:after:bg-sidebar-border",
        isResizing && "!transition-none",
      )}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerEnd}
      onPointerCancel={handlePointerEnd}
      onLostPointerCapture={handlePointerEnd}
      onKeyDown={handleKeyDown}
    />
  );
}
