// frontend/src/lib/components/AddWorktreeDialog.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    AlertTriangle,
    ChevronsUpDown,
    GitBranch,
    RefreshCw,
    Sparkles,
  } from "@lucide/svelte";
  import {
    listProjectWorktreeStartPoints,
    type WorktreeStartPoint,
  } from "$lib/api";
  import { getThemeStore } from "$lib/stores/theme.svelte";
  import { deterministicTagStyle } from "$lib/theme/deterministicTagColor";
  import { generateWorktreeBranchName } from "$lib/worktreeName";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import * as Command from "$lib/components/ui/command/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import * as Popover from "$lib/components/ui/popover/index.js";

  let {
    projectId,
    projectName,
    onAdd,
    onClose,
  }: {
    projectId: string;
    projectName: string;
    onAdd: (branch: string, startPoint?: string) => Promise<void>;
    onClose: () => void;
  } = $props();

  let branch = $state("");
  let suggestedBranch = $state(generateWorktreeBranchName());
  let startPointPopoverOpen = $state(false);
  let selectedStartPointValue = $state("");
  let useCustomStartPoint = $state(false);
  let customStartPoint = $state("");
  let startPoints = $state<WorktreeStartPoint[]>([]);
  let defaultStartPoint = $state("");
  let startPointWarning = $state("");
  let submitting = $state(false);
  let error = $state("");
  const themeStore = getThemeStore();
  const themeVersion = $derived(themeStore.version);
  const branchBadgeClass =
    "deterministic-tag-badge max-w-full truncate text-xs";

  function branchColorKey(
    ref: string,
    kind: "local" | "remote" = "local",
  ): string {
    const trimmed = ref.trim();
    if (!trimmed) {
      return "default";
    }

    if (trimmed.startsWith("refs/heads/")) {
      return trimmed.slice("refs/heads/".length);
    }

    if (trimmed.startsWith("refs/remotes/")) {
      const remainder = trimmed.slice("refs/remotes/".length);
      const slashIndex = remainder.indexOf("/");
      return slashIndex === -1 ? remainder : remainder.slice(slashIndex + 1);
    }

    if (kind === "remote") {
      const slashIndex = trimmed.indexOf("/");
      if (slashIndex > 0) {
        return trimmed.slice(slashIndex + 1);
      }
    }

    return trimmed;
  }

  function branchBadgeStyle(
    ref: string,
    kind: "local" | "remote" = "local",
  ): string {
    void themeVersion;
    return deterministicTagStyle(branchColorKey(ref, kind), {
      profile: "balanced",
      surfaceVar: "--popover",
    });
  }

  const selectedStartPoint = $derived(
    startPoints.find(
      (startPoint) => startPoint.value === selectedStartPointValue,
    ) ?? null,
  );

  const hasStartPointOptions = $derived(startPoints.length > 0);
  const startPointTriggerLabel = $derived.by(() => {
    if (useCustomStartPoint) {
      return customStartPoint.trim() || "Custom ref…";
    }
    if (selectedStartPoint?.local_ref) {
      return selectedStartPoint.local_ref;
    }
    if (selectedStartPoint?.remote_refs?.length) {
      return selectedStartPoint.remote_refs[0];
    }
    if (defaultStartPoint) {
      return defaultStartPoint;
    }
    return "Select start point";
  });

  onMount(() => {
    void loadStartPoints();
  });

  async function loadStartPoints(): Promise<void> {
    startPointWarning = "";
    try {
      const response = await listProjectWorktreeStartPoints(projectId);
      startPoints = response.start_points;
      defaultStartPoint = response.default_start_point?.trim() ?? "";

      if (!useCustomStartPoint) {
        const matchedDefault = defaultStartPoint
          ? response.start_points.find(
              (startPoint) =>
                startPoint.value === defaultStartPoint ||
                startPoint.local_ref === defaultStartPoint ||
                startPoint.remote_refs.includes(defaultStartPoint),
            )
          : undefined;

        selectedStartPointValue =
          matchedDefault?.value ||
          response.start_points[0]?.value ||
          selectedStartPointValue;
      }
      if (response.git_error) {
        startPointWarning = response.git_error;
      }
    } catch (err) {
      startPointWarning = `Failed to load branches (${(err as Error).message})`;
      startPoints = [];
      defaultStartPoint = "";
      if (!useCustomStartPoint) {
        selectedStartPointValue = "";
      }
    }
  }

  function rerollSuggestedBranch(): void {
    suggestedBranch = generateWorktreeBranchName(suggestedBranch);
  }

  function selectStartPoint(value: string): void {
    selectedStartPointValue = value;
    useCustomStartPoint = false;
    startPointPopoverOpen = false;
    error = "";
  }

  function selectCustomStartPoint(): void {
    useCustomStartPoint = true;
    startPointPopoverOpen = false;
    error = "";
  }

  async function submit() {
    const effectiveBranch = branch.trim() || suggestedBranch;
    if (!effectiveBranch) {
      return;
    }

    let effectiveStartPoint: string | undefined;
    if (useCustomStartPoint) {
      const custom = customStartPoint.trim();
      if (!custom) {
        error = "Custom start point is required.";
        return;
      }
      effectiveStartPoint = custom;
    } else {
      effectiveStartPoint =
        selectedStartPointValue || defaultStartPoint || undefined;
    }

    submitting = true;
    error = "";
    try {
      await onAdd(effectiveBranch, effectiveStartPoint);
    } catch (err) {
      error = (err as Error).message;
      submitting = false;
    }
  }
</script>

<Dialog.Root
  open
  onOpenChange={(open) => {
    if (!open) {
      onClose();
    }
  }}
>
  <Dialog.Content class="sm:max-w-md">
    <Dialog.Header>
      <Dialog.Title>New Worktree</Dialog.Title>
      <Dialog.Description>
        Create a new linked worktree for {projectName} from a new branch.
      </Dialog.Description>
    </Dialog.Header>

    <div class="space-y-3 py-2" data-theme-version={themeVersion}>
      <div class="space-y-1.5">
        <label for="new-worktree-branch" class="text-sm font-medium">
          Branch name
        </label>
        <div class="flex items-center gap-2">
          <Input
            id="new-worktree-branch"
            type="text"
            bind:value={branch}
            placeholder={suggestedBranch}
            class="flex-1"
            disabled={submitting}
            onkeydown={(e: KeyboardEvent) => {
              if (e.key === "Enter") {
                submit();
              }
            }}
          />
          <Button
            variant="outline"
            size="icon-sm"
            title="Generate another name"
            aria-label="Generate another name"
            disabled={submitting}
            onclick={rerollSuggestedBranch}
          >
            <RefreshCw class="h-4 w-4" />
          </Button>
        </div>
      </div>

      <div class="space-y-1.5">
        <label for="new-worktree-start-point" class="text-sm font-medium">
          Start from
        </label>
        <Popover.Root bind:open={startPointPopoverOpen}>
          <Popover.Trigger
            id="new-worktree-start-point"
            disabled={submitting}
            role="combobox"
            aria-expanded={startPointPopoverOpen}
            class="border-input ring-offset-background focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive flex h-9 w-full items-center justify-between rounded-md border bg-transparent px-3 py-2 text-sm shadow-xs transition-[color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50 focus-visible:ring-[3px]"
          >
            <span
              class="flex min-w-0 flex-1 items-center gap-1.5 overflow-hidden text-left"
            >
              {#if useCustomStartPoint}
                <Badge variant="outline" class="text-xs">Custom</Badge>
                <span class="truncate">{startPointTriggerLabel}</span>
              {:else if selectedStartPoint}
                {#if selectedStartPoint.local_ref}
                  <Badge
                    variant="outline"
                    class={branchBadgeClass}
                    style={branchBadgeStyle(selectedStartPoint.local_ref)}
                  >
                    {selectedStartPoint.local_ref}
                  </Badge>
                {/if}
                {#if !selectedStartPoint.local_ref && selectedStartPoint.remote_refs.length === 0}
                  <span class="truncate text-muted-foreground">
                    {startPointTriggerLabel}
                  </span>
                {/if}
                {#each selectedStartPoint.remote_refs as remoteRef (remoteRef)}
                  <Badge
                    variant="outline"
                    class={branchBadgeClass}
                    style={branchBadgeStyle(remoteRef, "remote")}
                  >
                    {remoteRef}
                  </Badge>
                {/each}
              {:else}
                <span class="truncate text-muted-foreground">
                  {startPointTriggerLabel}
                </span>
              {/if}
            </span>
            <ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
          </Popover.Trigger>
          <Popover.Content
            class="start-point-popover w-(--bits-popover-anchor-width) p-0"
            align="start"
          >
            <Command.Root class="start-point-command">
              <Command.Input
                class="start-point-command-input"
                placeholder="Search branches..."
              />
              <Command.List>
                <Command.Empty>No start points found.</Command.Empty>
                {#if hasStartPointOptions}
                  <Command.Group heading="Branches">
                    {#each startPoints as startPoint (startPoint.value)}
                      <Command.Item
                        value={startPoint.value}
                        keywords={[
                          startPoint.value,
                          startPoint.sha,
                          startPoint.local_ref ?? "",
                          ...startPoint.remote_refs,
                        ]}
                        class="start-point-command-item"
                        onSelect={() => selectStartPoint(startPoint.value)}
                      >
                        <GitBranch class="h-4 w-4 text-muted-foreground" />
                        <div class="min-w-0 flex-1">
                          <div
                            class="flex min-w-0 flex-wrap items-center gap-1"
                          >
                            {#if startPoint.local_ref}
                              <Badge
                                variant="outline"
                                class={branchBadgeClass}
                                style={branchBadgeStyle(startPoint.local_ref)}
                              >
                                {startPoint.local_ref}
                              </Badge>
                            {/if}
                            {#each startPoint.remote_refs as remoteRef (remoteRef)}
                              <Badge
                                variant="outline"
                                class={branchBadgeClass}
                                style={branchBadgeStyle(remoteRef, "remote")}
                              >
                                {remoteRef}
                              </Badge>
                            {/each}
                            {#if !startPoint.local_ref && startPoint.remote_refs.length === 0}
                              <span class="truncate">{startPoint.value}</span>
                            {/if}
                          </div>
                          <p class="mt-1 text-[11px] text-muted-foreground">
                            commit {startPoint.sha.slice(0, 8)}
                          </p>
                        </div>
                      </Command.Item>
                    {/each}
                  </Command.Group>
                {/if}
                <Command.Separator class="start-point-command-separator" />
                <Command.Group heading="Advanced">
                  <Command.Item
                    value="custom-ref-option"
                    keywords={["custom", "manual", "sha", "ref"]}
                    class="start-point-command-item"
                    onSelect={selectCustomStartPoint}
                  >
                    <Sparkles class="h-4 w-4 text-muted-foreground" />
                    <div class="flex flex-col">
                      <span>Custom ref…</span>
                      <span class="text-xs text-muted-foreground">
                        Use a tag, hash, or custom revision
                      </span>
                    </div>
                  </Command.Item>
                </Command.Group>
              </Command.List>
            </Command.Root>
          </Popover.Content>
        </Popover.Root>

        {#if useCustomStartPoint}
          <Input
            id="new-worktree-custom-start-point"
            type="text"
            bind:value={customStartPoint}
            placeholder={defaultStartPoint || "origin/main or commit SHA"}
            disabled={submitting}
            oninput={() => {
              if (error === "Custom start point is required.") {
                error = "";
              }
            }}
            onkeydown={(e: KeyboardEvent) => {
              if (e.key === "Enter") {
                submit();
              }
            }}
          />
        {/if}
      </div>

      {#if startPointWarning}
        <p class="flex items-center gap-1.5 text-xs text-amber-600">
          <AlertTriangle class="h-3.5 w-3.5 shrink-0" />
          {startPointWarning}
        </p>
      {/if}

      {#if error}
        <p class="text-sm text-destructive">{error}</p>
      {/if}
    </div>

    <Dialog.Footer>
      <Button variant="outline" onclick={onClose} disabled={submitting}>
        Cancel
      </Button>
      <Button onclick={submit} disabled={submitting}>Create</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

<style>
  :global(.start-point-popover) {
    background-color: var(--quick-input-background, var(--popover));
    border-color: var(--quick-input-border, var(--border));
    color: var(--quick-input-foreground, var(--popover-foreground));
    box-shadow: 0 14px 36px
      color-mix(
        in oklab,
        var(--quick-input-border, var(--border)) 22%,
        transparent
      );
  }

  :global(.start-point-command) {
    background-color: transparent;
    color: inherit;
  }

  :global(.start-point-popover [data-slot="command-input-wrapper"]) {
    border-color: color-mix(
      in oklab,
      var(--quick-input-border, var(--border)) 78%,
      transparent
    );
    background-color: color-mix(
      in oklab,
      var(--quick-input-background, var(--popover)) 90%,
      var(--background)
    );
  }

  :global(.start-point-popover [cmdk-group-heading]) {
    color: var(--quick-input-group-foreground, var(--muted-foreground));
  }

  :global(.start-point-command-separator) {
    background-color: color-mix(
      in oklab,
      var(--quick-input-border, var(--border)) 74%,
      transparent
    );
  }

  :global(.start-point-command-item[aria-selected="true"]) {
    background-color: var(
      --quick-input-focus-background,
      var(--accent)
    ) !important;
    color: var(
      --quick-input-focus-foreground,
      var(--accent-foreground)
    ) !important;
  }

  :global(.deterministic-tag-badge) {
    border-color: color-mix(
      in oklab,
      var(--tag-seed) calc(var(--tag-border-mix) * 1%),
      var(--border)
    );
    background-color: color-mix(
      in oklab,
      var(--tag-seed) calc(var(--tag-bg-mix) * 1%),
      var(--popover)
    );
    color: color-mix(
      in oklab,
      var(--tag-seed) calc(var(--tag-fg-mix) * 1%),
      var(--foreground)
    );
  }
</style>

// apps/web/src/components/AddWorktreeDialog.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  AlertTriangle,
  ChevronsUpDown,
  Download,
  GitBranch,
  Loader2,
  RefreshCw,
  Sparkles,
} from "lucide-react";
import {
  type ImportableWorktree,
  type WorktreeStartPoint,
  listImportableWorktrees,
  listProjectWorktreeStartPoints,
} from "@/lib/api";
import { tagStyle } from "@/lib/theme/tagStyle";
import { generateWorktreeBranchName } from "@/lib/worktreeName";
import { useThemeSettings } from "@/lib/stores/theme";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from "@/components/ui/command";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { Popover, PopoverTrigger } from "@/components/ui/popover";
import { Popover as PopoverPrimitive } from "radix-ui";

type Props = {
  projectId: string;
  projectName: string;
  onAdd: (
    branch: string,
    startPoint?: string,
    sourceRef?: string,
  ) => Promise<void>;
  onImport: (path: string) => Promise<void>;
  onClose: () => void;
};

type ActiveTab = "create" | "import";

function DialogScopedPopoverContent({
  portalContainer,
  className,
  align = "center",
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Content> & {
  portalContainer: HTMLElement | null;
}) {
  return (
    <PopoverPrimitive.Portal container={portalContainer ?? undefined}>
      <PopoverPrimitive.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(
          "pointer-events-auto z-50 w-72 origin-(--radix-popover-content-transform-origin) rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-hidden data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
          className,
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  );
}

function TabButton({
  active,
  children,
  onClick,
}: {
  active: boolean;
  children: React.ReactNode;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      className={cn(
        "flex-1 rounded-md px-3 py-1.5 text-sm font-medium",
        "transition-colors",
        active
          ? "bg-background text-foreground shadow-sm"
          : "text-muted-foreground hover:text-foreground",
      )}
      onClick={onClick}
    >
      {children}
    </button>
  );
}

type CreatePanelHandle = { submit: () => void };

const CreatePanel = forwardRef<
  CreatePanelHandle,
  {
    projectId: string;
    submitting: boolean;
    onSubmit: (
      branch: string,
      startPoint?: string,
      sourceRef?: string,
    ) => Promise<void>;
  }
>(function CreatePanel({ projectId, submitting, onSubmit }, ref) {
  const themeVersion = useThemeSettings((state) => state.version);
  const [branch, setBranch] = useState("");
  const [suggestedBranch, setSuggestedBranch] = useState(
    generateWorktreeBranchName(),
  );
  const [startPointPopoverOpen, setStartPointPopoverOpen] = useState(false);
  const [selectedStartPointValue, setSelectedStartPointValue] = useState("");
  const [useCustomStartPoint, setUseCustomStartPoint] = useState(false);
  const [customStartPoint, setCustomStartPoint] = useState("");
  const [startPoints, setStartPoints] = useState<WorktreeStartPoint[]>([]);
  const [defaultStartPoint, setDefaultStartPoint] = useState("");
  const [startPointWarning, setStartPointWarning] = useState("");
  const [error, setError] = useState("");
  const [startPointPopoverContainer, setStartPointPopoverContainer] =
    useState<HTMLDivElement | null>(null);

  const selectedStartPoint = useMemo(
    () =>
      startPoints.find(
        (startPoint) => startPoint.value === selectedStartPointValue,
      ) ?? null,
    [selectedStartPointValue, startPoints],
  );

  const startPointTriggerLabel = useMemo(() => {
    if (useCustomStartPoint) {
      return customStartPoint.trim() || "Custom ref…";
    }
    if (selectedStartPoint?.localRef) {
      return selectedStartPoint.localRef;
    }
    if (selectedStartPoint?.remoteRefs?.length) {
      return selectedStartPoint.remoteRefs[0];
    }
    if (defaultStartPoint) {
      return defaultStartPoint;
    }
    return "Select start point";
  }, [
    customStartPoint,
    defaultStartPoint,
    selectedStartPoint,
    useCustomStartPoint,
  ]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      void (async () => {
        setStartPointWarning("");
        try {
          const response = await listProjectWorktreeStartPoints(projectId);
          setStartPoints(response.startPoints);
          const nextDefault = response.defaultStartPoint?.trim() ?? "";
          setDefaultStartPoint(nextDefault);
          const matchedDefault = nextDefault
            ? response.startPoints.find(
                (startPoint) =>
                  startPoint.value === nextDefault ||
                  startPoint.localRef === nextDefault ||
                  startPoint.remoteRefs.includes(nextDefault),
              )
            : undefined;
          setSelectedStartPointValue(
            matchedDefault?.value || response.startPoints[0]?.value || "",
          );
          if (response.gitError) {
            setStartPointWarning(response.gitError);
          }
        } catch (loadError) {
          setStartPointWarning(
            `Failed to load branches (${(loadError as Error).message})`,
          );
          setStartPoints([]);
          setDefaultStartPoint("");
          setSelectedStartPointValue("");
        }
      })();
    }, 0);

    return () => window.clearTimeout(timer);
  }, [projectId]);

  async function submit(): Promise<void> {
    const effectiveBranch = branch.trim() || suggestedBranch;
    if (!effectiveBranch) {
      return;
    }

    let effectiveStartPoint: string | undefined;
    if (useCustomStartPoint) {
      const custom = customStartPoint.trim();
      if (!custom) {
        setError("Custom start point is required.");
        return;
      }
      effectiveStartPoint = custom;
    } else {
      effectiveStartPoint =
        selectedStartPointValue || defaultStartPoint || undefined;
    }

    setError("");
    try {
      const matchedStartPoint =
        useCustomStartPoint || !effectiveStartPoint
          ? undefined
          : startPoints.find(
              (startPoint) =>
                startPoint.value === effectiveStartPoint ||
                startPoint.localRef === effectiveStartPoint ||
                startPoint.remoteRefs.includes(effectiveStartPoint),
            );
      const sourceRef =
        matchedStartPoint?.remoteRefs[0] ??
        matchedStartPoint?.localRef ??
        undefined;

      await onSubmit(effectiveBranch, effectiveStartPoint, sourceRef);
    } catch (submitError) {
      setError((submitError as Error).message);
    }
  }

  useImperativeHandle(ref, () => ({ submit: () => void submit() }));

  return (
    <>
      <div
        ref={setStartPointPopoverContainer}
        className="pointer-events-none absolute inset-0 z-50"
        data-start-point-popover-container
      />
      <div className="space-y-3 py-2" data-theme-version={themeVersion}>
        <div className="space-y-1.5">
          <label htmlFor="new-worktree-branch" className="text-sm font-medium">
            Branch name
          </label>
          <div className="flex items-center gap-2">
            <Input
              id="new-worktree-branch"
              type="text"
              value={branch}
              placeholder={suggestedBranch}
              className="flex-1"
              disabled={submitting}
              onChange={(event) => setBranch(event.currentTarget.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  void submit();
                }
              }}
            />
            <Button
              variant="outline"
              size="icon-sm"
              title="Generate another name"
              aria-label="Generate another name"
              disabled={submitting}
              onClick={() =>
                setSuggestedBranch((value) => generateWorktreeBranchName(value))
              }
            >
              <RefreshCw className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="space-y-1.5">
          <label
            htmlFor="new-worktree-start-point"
            className="text-sm font-medium"
          >
            Start from
          </label>
          <Popover
            open={startPointPopoverOpen}
            onOpenChange={setStartPointPopoverOpen}
          >
            <PopoverTrigger asChild>
              <Button
                id="new-worktree-start-point"
                variant="outline"
                disabled={submitting}
                role="combobox"
                aria-expanded={startPointPopoverOpen}
                className="h-auto w-full justify-between px-3 py-2"
              >
                <span className="flex min-w-0 flex-1 items-center gap-1.5 overflow-hidden text-left">
                  {useCustomStartPoint ? (
                    <>
                      <Badge variant="outline" className="text-xs">
                        Custom
                      </Badge>
                      <span className="truncate">{startPointTriggerLabel}</span>
                    </>
                  ) : selectedStartPoint ? (
                    <>
                      {selectedStartPoint.localRef ? (
                        <Badge
                          variant="outline"
                          className="deterministic-tag-badge max-w-full truncate text-xs"
                          style={tagStyle(selectedStartPoint.localRef)}
                        >
                          {selectedStartPoint.localRef}
                        </Badge>
                      ) : null}
                      {!selectedStartPoint.localRef &&
                      selectedStartPoint.remoteRefs.length === 0 ? (
                        <span className="truncate text-muted-foreground">
                          {startPointTriggerLabel}
                        </span>
                      ) : null}
                      {selectedStartPoint.remoteRefs.map((remoteRef) => (
                        <Badge
                          key={remoteRef}
                          variant="outline"
                          className="deterministic-tag-badge max-w-full truncate text-xs"
                          style={tagStyle(remoteRef, "remote")}
                        >
                          {remoteRef}
                        </Badge>
                      ))}
                    </>
                  ) : (
                    <span className="truncate text-muted-foreground">
                      {startPointTriggerLabel}
                    </span>
                  )}
                </span>
                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
              </Button>
            </PopoverTrigger>
            <DialogScopedPopoverContent
              portalContainer={startPointPopoverContainer}
              className="start-point-popover w-[var(--radix-popover-trigger-width)] p-0"
              align="start"
            >
              <Command className="start-point-command">
                <CommandInput
                  className="start-point-command-input"
                  placeholder="Search branches..."
                />
                <CommandList>
                  <CommandEmpty>No start points found.</CommandEmpty>
                  {startPoints.length > 0 ? (
                    <CommandGroup heading="Branches">
                      {startPoints.map((startPoint) => (
                        <CommandItem
                          key={startPoint.value}
                          value={startPoint.value}
                          keywords={[
                            startPoint.value,
                            startPoint.sha,
                            startPoint.localRef ?? "",
                            ...startPoint.remoteRefs,
                          ]}
                          className="start-point-command-item"
                          onSelect={() => {
                            setSelectedStartPointValue(startPoint.value);
                            setUseCustomStartPoint(false);
                            setStartPointPopoverOpen(false);
                            setError("");
                          }}
                        >
                          <GitBranch className="h-4 w-4 text-muted-foreground" />
                          <div className="min-w-0 flex-1">
                            <div className="flex min-w-0 flex-wrap items-center gap-1">
                              {startPoint.localRef ? (
                                <Badge
                                  variant="outline"
                                  className="deterministic-tag-badge max-w-full truncate text-xs"
                                  style={tagStyle(startPoint.localRef)}
                                >
                                  {startPoint.localRef}
                                </Badge>
                              ) : null}
                              {startPoint.remoteRefs.map((remoteRef) => (
                                <Badge
                                  key={remoteRef}
                                  variant="outline"
                                  className="deterministic-tag-badge max-w-full truncate text-xs"
                                  style={tagStyle(remoteRef, "remote")}
                                >
                                  {remoteRef}
                                </Badge>
                              ))}
                              {!startPoint.localRef &&
                              startPoint.remoteRefs.length === 0 ? (
                                <span className="truncate">
                                  {startPoint.value}
                                </span>
                              ) : null}
                            </div>
                            <p className="mt-1 text-[11px] text-muted-foreground">
                              commit {startPoint.sha.slice(0, 8)}
                            </p>
                          </div>
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  ) : null}
                  <CommandSeparator className="start-point-command-separator" />
                  <CommandGroup heading="Advanced">
                    <CommandItem
                      value="custom-ref-option"
                      keywords={["custom", "manual", "sha", "ref"]}
                      className="start-point-command-item"
                      onSelect={() => {
                        setUseCustomStartPoint(true);
                        setStartPointPopoverOpen(false);
                        setError("");
                      }}
                    >
                      <Sparkles className="h-4 w-4 text-muted-foreground" />
                      <div className="flex flex-col">
                        <span>Custom ref…</span>
                        <span className="text-xs text-muted-foreground">
                          Use a tag, hash, or custom revision
                        </span>
                      </div>
                    </CommandItem>
                  </CommandGroup>
                </CommandList>
              </Command>
            </DialogScopedPopoverContent>
          </Popover>

          {useCustomStartPoint ? (
            <Input
              id="new-worktree-custom-start-point"
              type="text"
              value={customStartPoint}
              placeholder={defaultStartPoint || "origin/main or commit SHA"}
              disabled={submitting}
              onChange={(event) => {
                setCustomStartPoint(event.currentTarget.value);
                if (error === "Custom start point is required.") {
                  setError("");
                }
              }}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  void submit();
                }
              }}
            />
          ) : null}
        </div>

        {startPointWarning ? (
          <p className="flex items-center gap-1.5 text-xs text-amber-600">
            <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
            {startPointWarning}
          </p>
        ) : null}

        {error ? <p className="text-sm text-destructive">{error}</p> : null}
      </div>
    </>
  );
});

function ImportPanel({
  projectId,
  submitting,
  selectedPath,
  onSelect,
}: {
  projectId: string;
  submitting: boolean;
  selectedPath: string | null;
  onSelect: (path: string | null) => void;
}) {
  const [worktrees, setWorktrees] = useState<ImportableWorktree[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError("");
    void (async () => {
      try {
        const response = await listImportableWorktrees(projectId);
        if (cancelled) return;
        setWorktrees(response.importableWorktrees);
        if (response.gitError) {
          setError(response.gitError);
        }
      } catch (loadError) {
        if (cancelled) return;
        setError(`Failed to list worktrees (${(loadError as Error).message})`);
        setWorktrees([]);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [projectId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8">
        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error && worktrees.length === 0) {
    return (
      <p className="flex items-center gap-1.5 py-4 text-sm text-amber-600">
        <AlertTriangle className="h-4 w-4 shrink-0" />
        {error}
      </p>
    );
  }

  if (worktrees.length === 0) {
    return (
      <div className="py-6 text-center">
        <Download className="mx-auto mb-2 h-8 w-8 text-muted-foreground/50" />
        <p className="text-sm text-muted-foreground">
          No external worktrees found.
        </p>
        <p className="mt-1 text-xs text-muted-foreground/70">
          Create worktrees outside Hubris with{" "}
          <code className="rounded bg-muted px-1 py-0.5">git worktree add</code>{" "}
          and they will appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-2 py-2">
      {error ? (
        <p className="flex items-center gap-1.5 text-xs text-amber-600">
          <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
          {error}
        </p>
      ) : null}
      <div className="max-h-56 space-y-1 overflow-y-auto">
        {worktrees.map((wt) => (
          <button
            key={wt.id}
            type="button"
            disabled={submitting}
            className={cn(
              "flex w-full items-start gap-3 rounded-lg border p-3",
              "text-left transition-colors",
              selectedPath === wt.path
                ? "border-primary/40 bg-primary/5"
                : "border-transparent bg-muted/25 hover:bg-muted/50",
            )}
            onClick={() => onSelect(selectedPath === wt.path ? null : wt.path)}
          >
            <GitBranch className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
            <div className="min-w-0 flex-1">
              {wt.branch ? (
                <p className="truncate text-sm font-medium">{wt.branch}</p>
              ) : null}
              <p className="truncate text-xs text-muted-foreground">
                {wt.path}
              </p>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

export default function AddWorktreeDialog({
  projectId,
  projectName,
  onAdd,
  onImport,
  onClose,
}: Props) {
  const [activeTab, setActiveTab] = useState<ActiveTab>("create");
  const createPanelRef = useRef<CreatePanelHandle | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [importSelectedPath, setImportSelectedPath] = useState<string | null>(
    null,
  );
  const [importError, setImportError] = useState("");

  async function handleCreate(
    branch: string,
    startPoint?: string,
    sourceRef?: string,
  ): Promise<void> {
    setSubmitting(true);
    try {
      await onAdd(branch, startPoint, sourceRef);
    } catch (error) {
      setSubmitting(false);
      throw error;
    }
  }

  async function handleImport(): Promise<void> {
    if (!importSelectedPath) return;
    setSubmitting(true);
    setImportError("");
    try {
      await onImport(importSelectedPath);
    } catch (error) {
      setImportError((error as Error).message);
      setSubmitting(false);
    }
  }

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {activeTab === "create" ? "New Worktree" : "Import Worktree"}
          </DialogTitle>
          <DialogDescription>
            {activeTab === "create"
              ? `Create a new linked worktree for ${projectName} from a new branch.`
              : `Import an existing git worktree into ${projectName}.`}
          </DialogDescription>
        </DialogHeader>

        <div className="flex gap-1 rounded-lg border bg-muted/40 p-1">
          <TabButton
            active={activeTab === "create"}
            onClick={() => setActiveTab("create")}
          >
            Create
          </TabButton>
          <TabButton
            active={activeTab === "import"}
            onClick={() => setActiveTab("import")}
          >
            Import
          </TabButton>
        </div>

        {activeTab === "create" ? (
          <CreatePanel
            ref={createPanelRef}
            projectId={projectId}
            submitting={submitting}
            onSubmit={handleCreate}
          />
        ) : (
          <>
            <ImportPanel
              projectId={projectId}
              submitting={submitting}
              selectedPath={importSelectedPath}
              onSelect={setImportSelectedPath}
            />
            {importError ? (
              <p className="text-sm text-destructive">{importError}</p>
            ) : null}
          </>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={submitting}>
            Cancel
          </Button>
          {activeTab === "create" ? (
            <Button
              disabled={submitting}
              onClick={() => createPanelRef.current?.submit()}
            >
              Create
            </Button>
          ) : (
            <Button
              disabled={submitting || !importSelectedPath}
              onClick={() => void handleImport()}
            >
              Import
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
