// frontend/src/lib/components/FileBrowser.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import { listFiles } from "$lib/api";
  import type { DirEntry } from "$lib/types";
  import * as ScrollArea from "$lib/components/ui/scroll-area/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Skeleton } from "$lib/components/ui/skeleton/index.js";
  import {
    Folder,
    FolderGit2,
    House,
    ArrowUp,
    RotateCcw,
    Eye,
    EyeOff,
  } from "@lucide/svelte";

  let {
    currentPath = $bindable(""),
    onSelect,
  }: {
    currentPath: string;
    onSelect: (path: string) => void;
  } = $props();

  let entries = $state<DirEntry[]>([]);
  let loading = $state(false);
  let error = $state("");
  let homeDir = $state<string | null>(null);
  let showHidden = $state(false);
  let focusedIndex = $state(-1);

  // The path currently displayed in the browser.
  // May differ from currentPath during user typing.
  let browsedPath = $state("");

  // Breadcrumb segments derived from browsedPath
  let pathSegments = $derived.by(() => {
    if (!browsedPath) return [];
    const parts = browsedPath.split("/").filter(Boolean);
    return parts.map((part, i) => ({
      name: part,
      path: "/" + parts.slice(0, i + 1).join("/"),
    }));
  });

  async function fetchEntries(path?: string) {
    loading = true;
    error = "";
    focusedIndex = -1;
    try {
      const res = await listFiles(path, showHidden);
      entries = res.entries;
      browsedPath = res.path;
      currentPath = res.path;
      if (res.home_dir) homeDir = res.home_dir;
    } catch (e) {
      error = (e as Error).message;
      entries = [];
    } finally {
      loading = false;
    }
  }

  function navigateTo(path: string) {
    fetchEntries(path);
  }

  function navigateToEntry(entry: DirEntry) {
    const sep = browsedPath.endsWith("/") ? "" : "/";
    navigateTo(browsedPath + sep + entry.name);
  }

  function navigateToParent() {
    const parent = browsedPath.replace(/\/[^/]+\/?$/, "") || "/";
    navigateTo(parent);
  }

  // Initial load — fetch home directory once on mount
  $effect(() => {
    untrack(() => fetchEntries());
  });

  // Watch for external currentPath changes (user typing)
  let debounceTimer: ReturnType<typeof setTimeout>;
  $effect(() => {
    const path = currentPath;
    if (path === browsedPath) return;

    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      if (path.trim()) {
        fetchEntries(path);
      }
    }, 400);

    return () => clearTimeout(debounceTimer);
  });

  // Watch showHidden toggle — re-fetch, skip initial run
  let showHiddenInitialized = false;
  $effect(() => {
    void showHidden;
    if (!showHiddenInitialized) {
      showHiddenInitialized = true;
      return;
    }
    if (browsedPath) {
      fetchEntries(browsedPath);
    }
  });

  function handleKeydown(e: KeyboardEvent) {
    if (entries.length === 0) return;

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        focusedIndex = Math.min(focusedIndex + 1, entries.length - 1);
        break;
      case "ArrowUp":
        e.preventDefault();
        focusedIndex = Math.max(focusedIndex - 1, 0);
        break;
      case "Enter":
        e.preventDefault();
        if (focusedIndex >= 0) {
          navigateToEntry(entries[focusedIndex]);
        }
        break;
      case "Backspace":
        e.preventDefault();
        navigateToParent();
        break;
    }
  }
</script>

<!-- Breadcrumb navigation -->
<div
  class="flex items-center gap-0 overflow-x-auto
         text-[13px] font-mono text-muted-foreground
         pb-2 [scrollbar-width:none]
         [&::-webkit-scrollbar]:hidden"
>
  <button
    class="shrink-0 px-1 hover:text-foreground
           transition-colors"
    onclick={() => navigateTo("/")}>/</button
  >
  {#each pathSegments as segment (segment.path)}
    <button
      class="shrink-0 truncate max-w-[140px] px-0.5
             hover:text-foreground hover:underline
             underline-offset-2 transition-colors"
      onclick={() => navigateTo(segment.path)}>{segment.name}</button
    >
    <span class="shrink-0 opacity-40">/</span>
  {/each}
</div>

<!-- Toolbar -->
<div class="flex items-center gap-0.5 pb-2">
  {#if homeDir}
    <Button
      variant="ghost"
      size="icon-sm"
      onclick={() => navigateTo(homeDir!)}
      title="Home directory"
    >
      <House class="h-3.5 w-3.5" />
    </Button>
  {/if}
  <Button
    variant="ghost"
    size="icon-sm"
    onclick={navigateToParent}
    title="Parent directory"
  >
    <ArrowUp class="h-3.5 w-3.5" />
  </Button>
  <Button
    variant="ghost"
    size="icon-sm"
    onclick={() => fetchEntries(browsedPath)}
    title="Refresh"
  >
    <RotateCcw class="h-3.5 w-3.5" />
  </Button>
  <div class="flex-1"></div>
  <Button
    variant="ghost"
    size="icon-sm"
    onclick={() => (showHidden = !showHidden)}
    class={showHidden ? "text-foreground" : ""}
    title={showHidden ? "Hide dotfiles" : "Show dotfiles"}
  >
    {#if showHidden}
      <EyeOff class="h-3.5 w-3.5" />
    {:else}
      <Eye class="h-3.5 w-3.5" />
    {/if}
  </Button>
</div>

<!-- Directory listing -->
<ScrollArea.Root class="h-[280px] rounded-md border">
  <div class="p-1" role="listbox" tabindex="0" onkeydown={handleKeydown}>
    {#if loading}
      {#each Array(6) as _, i (i)}
        <div class="flex items-center gap-2 px-2 py-1.5">
          <Skeleton class="h-4 w-4 rounded" />
          <Skeleton class="h-4 w-32 rounded" />
        </div>
      {/each}
    {:else if error}
      <div
        class="flex flex-col items-center gap-2
               py-8 text-sm text-muted-foreground"
      >
        <p class="text-destructive">{error}</p>
        <Button
          variant="outline"
          size="sm"
          onclick={() => fetchEntries(browsedPath)}
        >
          Retry
        </Button>
      </div>
    {:else if entries.length === 0}
      <div
        class="px-2 py-6 text-[13px] font-mono
               text-muted-foreground/60"
      >
        (empty)
      </div>
    {:else}
      {#each entries as entry, i (entry.name)}
        <button
          class="flex w-full items-center gap-2
                 rounded-sm px-2 py-1 text-sm
                 text-left transition-colors
                 hover:bg-accent/50
                 {i === focusedIndex ? 'bg-accent text-accent-foreground' : ''}
                 {entry.is_git_repo
            ? 'border-l-2 border-primary'
            : 'border-l-2 border-transparent'}"
          onclick={() => navigateToEntry(entry)}
          ondblclick={() => {
            const sep = browsedPath.endsWith("/") ? "" : "/";
            onSelect(browsedPath + sep + entry.name);
          }}
          role="option"
          aria-selected={i === focusedIndex}
        >
          {#if entry.is_git_repo}
            <FolderGit2 class="h-4 w-4 shrink-0 text-primary" />
          {:else}
            <Folder
              class="h-4 w-4 shrink-0
                     text-muted-foreground"
            />
          {/if}
          <span class="truncate font-mono text-[13px]">
            {entry.name}
          </span>
        </button>
      {/each}
    {/if}
  </div>
</ScrollArea.Root>

// apps/web/src/components/FileBrowser.tsx
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
} from "react";
import {
  ArrowUp,
  Eye,
  EyeOff,
  Folder,
  FolderGit,
  House,
  RotateCcw,
} from "lucide-react";
import { TreeView, type TreeRowRenderProps } from "@/components/tree/TreeView";
import { listFiles } from "@/lib/api";
import type { DirEntry } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";

type Props = {
  currentPath: string;
  onCurrentPathChange: (path: string) => void;
  onSelect: (path: string) => void;
};

function getEntryPath(entry: DirEntry): string {
  return entry.name;
}

function FileBrowserRow({
  node: entry,
  selected,
  rowProps,
  onNavigate,
  onSelectEntry,
}: TreeRowRenderProps<DirEntry> & {
  onNavigate: (entry: DirEntry) => void;
  onSelectEntry: (entry: DirEntry) => void;
}) {
  return (
    <button
      {...rowProps}
      className={[
        "flex w-full items-center gap-2 rounded-sm border-l-2 px-2 py-1 text-left text-sm transition-colors hover:bg-accent/50",
        selected ? "bg-accent text-accent-foreground" : "",
        entry.is_git_repo ? "border-primary" : "border-transparent",
      ].join(" ")}
      onClick={() => onNavigate(entry)}
      onDoubleClick={() => onSelectEntry(entry)}
      type="button"
    >
      {entry.is_git_repo ? (
        <FolderGit className="h-4 w-4 shrink-0 text-primary" />
      ) : (
        <Folder className="h-4 w-4 shrink-0 text-muted-foreground" />
      )}
      <span className="truncate">{entry.name}</span>
    </button>
  );
}

export default function FileBrowser({
  currentPath,
  onCurrentPathChange,
  onSelect,
}: Props) {
  const [entries, setEntries] = useState<DirEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [homeDir, setHomeDir] = useState<string | null>(null);
  const [showHidden, setShowHidden] = useState(false);
  const [focusedPath, setFocusedPath] = useState<string | null>(null);
  const [browsedPath, setBrowsedPath] = useState("");
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const showHiddenRef = useRef(showHidden);
  const browsedPathRef = useRef("");

  useEffect(() => {
    showHiddenRef.current = showHidden;
  }, [showHidden]);

  useEffect(() => {
    browsedPathRef.current = browsedPath;
  }, [browsedPath]);

  const pathSegments = useMemo(() => {
    if (!browsedPath) {
      return [];
    }

    const parts = browsedPath.split("/").filter(Boolean);
    return parts.map((part, index) => ({
      name: part,
      path: `/${parts.slice(0, index + 1).join("/")}`,
    }));
  }, [browsedPath]);

  const fetchEntries = useCallback(
    async (
      path?: string,
      options?: { showHidden?: boolean },
    ): Promise<void> => {
      setLoading(true);
      setError("");
      setFocusedPath(null);

      try {
        const response = await listFiles(
          path,
          options?.showHidden ?? showHiddenRef.current,
        );
        setEntries(response.entries);
        setBrowsedPath(response.path);
        onCurrentPathChange(response.path);
        if (response.home_dir) {
          setHomeDir(response.home_dir);
        }
      } catch (fetchError) {
        setError((fetchError as Error).message);
        setEntries([]);
      } finally {
        setLoading(false);
      }
    },
    [onCurrentPathChange],
  );

  useEffect(() => {
    void fetchEntries();
  }, [fetchEntries]);

  useEffect(() => {
    if (currentPath === browsedPath) {
      return;
    }

    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }

    debounceRef.current = setTimeout(() => {
      if (currentPath.trim()) {
        void fetchEntries(currentPath);
      }
    }, 400);

    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, [browsedPath, currentPath, fetchEntries]);

  useEffect(() => {
    if (!browsedPathRef.current) {
      return;
    }

    void fetchEntries(browsedPathRef.current, { showHidden });
  }, [fetchEntries, showHidden]);

  const navigateTo = useCallback(
    (path: string): void => {
      void fetchEntries(path);
    },
    [fetchEntries],
  );

  const navigateToEntry = useCallback(
    (entry: DirEntry): void => {
      const separator = browsedPath.endsWith("/") ? "" : "/";
      navigateTo(`${browsedPath}${separator}${entry.name}`);
    },
    [browsedPath, navigateTo],
  );
  const selectEntry = useCallback(
    (entry: DirEntry): void => {
      const separator = browsedPath.endsWith("/") ? "" : "/";
      onSelect(`${browsedPath}${separator}${entry.name}`);
    },
    [browsedPath, onSelect],
  );

  const navigateToParent = useCallback((): void => {
    const parent = browsedPath.replace(/\/[^/]+\/?$/, "") || "/";
    navigateTo(parent);
  }, [browsedPath, navigateTo]);
  const handleTreeKeyDown = useCallback(
    (event: KeyboardEvent<HTMLElement>) => {
      if ((event.key === "s" || event.key === "S") && browsedPath) {
        event.preventDefault();
        onSelect(browsedPath);
      }
    },
    [browsedPath, onSelect],
  );
  const renderEntry = useCallback(
    (rowProps: TreeRowRenderProps<DirEntry>) => (
      <FileBrowserRow
        {...rowProps}
        onNavigate={navigateToEntry}
        onSelectEntry={selectEntry}
      />
    ),
    [navigateToEntry, selectEntry],
  );

  return (
    <>
      <div className="flex items-center gap-0 overflow-x-auto pb-2 text-[13px] font-mono text-muted-foreground [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        <button
          className="shrink-0 px-1 transition-colors hover:text-foreground"
          onClick={() => navigateTo("/")}
          type="button"
        >
          /
        </button>
        {pathSegments.map((segment) => (
          <span key={segment.path} className="flex shrink-0 items-center">
            <button
              className="max-w-[140px] truncate px-0.5 underline-offset-2 transition-colors hover:text-foreground hover:underline"
              onClick={() => navigateTo(segment.path)}
              type="button"
            >
              {segment.name}
            </button>
            <span className="shrink-0 opacity-40">/</span>
          </span>
        ))}
      </div>

      <div className="flex items-center gap-0.5 pb-2">
        {homeDir ? (
          <Button
            variant="ghost"
            size="icon-sm"
            onClick={() => navigateTo(homeDir)}
            title="Home directory"
          >
            <House className="h-3.5 w-3.5" />
          </Button>
        ) : null}
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={navigateToParent}
          title="Parent directory"
        >
          <ArrowUp className="h-3.5 w-3.5" />
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={() => void fetchEntries(browsedPath)}
          title="Refresh"
        >
          <RotateCcw className="h-3.5 w-3.5" />
        </Button>
        <div className="flex-1" />
        <Button
          variant="outline"
          size="sm"
          disabled={!browsedPath}
          onClick={() => {
            if (!browsedPath) {
              return;
            }
            onSelect(browsedPath);
          }}
        >
          Select folder
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={() => setShowHidden((value) => !value)}
          className={showHidden ? "text-foreground" : undefined}
          title={showHidden ? "Hide dotfiles" : "Show dotfiles"}
        >
          {showHidden ? (
            <EyeOff className="h-3.5 w-3.5" />
          ) : (
            <Eye className="h-3.5 w-3.5" />
          )}
        </Button>
      </div>

      <ScrollArea className="h-[280px] rounded-md border">
        <div className="p-1">
          {loading ? (
            Array.from({ length: 6 }).map((_, index) => (
              <div key={index} className="flex items-center gap-2 px-2 py-1.5">
                <Skeleton className="h-4 w-4 rounded" />
                <Skeleton className="h-4 w-32 rounded" />
              </div>
            ))
          ) : error ? (
            <div className="flex flex-col items-center gap-2 py-8 text-sm text-muted-foreground">
              <p className="text-destructive">{error}</p>
              <Button
                variant="outline"
                size="sm"
                onClick={() => void fetchEntries(browsedPath)}
              >
                Retry
              </Button>
            </div>
          ) : entries.length === 0 ? (
            <div className="px-2 py-6 text-[13px] font-mono text-muted-foreground/60">
              (empty)
            </div>
          ) : (
            <TreeView
              nodes={entries}
              role="listbox"
              tabIndex={0}
              focusedPath={focusedPath}
              onFocusedPathChange={setFocusedPath}
              onActivate={navigateToEntry}
              onNavigateParent={navigateToParent}
              onKeyDown={handleTreeKeyDown}
              getPath={getEntryPath}
              renderRow={renderEntry}
            />
          )}
        </div>
      </ScrollArea>
    </>
  );
}
