// frontend/src/lib/components/settings/TerminalSettings.svelte
<script lang="ts">
  import * as Select from "$lib/components/ui/select/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Label } from "$lib/components/ui/label/index.js";
  import { getTerminalStore } from "$lib/stores/terminal.svelte";
  import { BUNDLED_FONTS } from "$lib/terminal/fonts";
  import { Type, Minus, Plus } from "@lucide/svelte";

  const termStore = getTerminalStore();

  const fontPreviewLines = [
    "Hello, World!",
    "ABCDEFGHIJKLM 0123456789",
    "abcdefghijklm ~!@#$%^&*()",
  ];
</script>

<section class="space-y-3">
  <h3 class="text-sm font-medium">Font</h3>

  <!-- Font Source -->
  <div class="grid grid-cols-[120px_1fr] items-center gap-3">
    <Label>Source</Label>
    <div class="flex gap-1">
      <Button
        variant={termStore.settings.fontSource === "default"
          ? "secondary"
          : "ghost"}
        size="sm"
        onclick={() =>
          termStore.updateSettings({
            fontSource: "default",
          })}
      >
        Default
      </Button>
      <Button
        variant={termStore.settings.fontSource === "system"
          ? "secondary"
          : "ghost"}
        size="sm"
        onclick={() =>
          termStore.updateSettings({
            fontSource: "system",
          })}
      >
        System
      </Button>
      <Button
        variant={termStore.settings.fontSource === "bundled"
          ? "secondary"
          : "ghost"}
        size="sm"
        onclick={() =>
          termStore.updateSettings({
            fontSource: "bundled",
          })}
      >
        <Type class="mr-1.5 h-3.5 w-3.5" />
        Bundled
      </Button>
    </div>
  </div>

  <!-- System font input -->
  {#if termStore.settings.fontSource === "system"}
    <div class="grid grid-cols-[120px_1fr] items-center gap-3">
      <Label>Font Family</Label>
      <Input
        type="text"
        placeholder="'My Font', monospace"
        value={termStore.settings.systemFontFamily}
        onchange={(e) =>
          termStore.updateSettings({
            systemFontFamily: e.currentTarget.value,
          })}
      />
    </div>
  {/if}

  <!-- Bundled font picker -->
  {#if termStore.settings.fontSource === "bundled"}
    <div class="grid grid-cols-[120px_1fr] items-center gap-3">
      <Label>Bundled Font</Label>
      <Select.Root
        type="single"
        value={termStore.settings.bundledFont}
        onValueChange={(v) => {
          if (v)
            termStore.updateSettings({
              bundledFont: v,
            });
        }}
      >
        <Select.Trigger class="w-full">
          <span data-slot="select-value">
            {BUNDLED_FONTS.find((f) => f.id === termStore.settings.bundledFont)
              ?.name ?? "Select…"}
          </span>
        </Select.Trigger>
        <Select.Content>
          {#each BUNDLED_FONTS as font (font.id)}
            <Select.Item value={font.id} label={font.name}>
              {font.name}
            </Select.Item>
          {/each}
        </Select.Content>
      </Select.Root>
    </div>
  {/if}

  <!-- Font Size -->
  <div class="grid grid-cols-[120px_1fr] items-center gap-3">
    <Label>Font Size</Label>
    <div class="flex items-center gap-1">
      <Button
        variant="outline"
        size="icon-sm"
        disabled={termStore.settings.fontSize <= 8}
        onclick={() =>
          termStore.updateSettings({
            fontSize: termStore.settings.fontSize - 1,
          })}
      >
        <Minus class="h-3.5 w-3.5" />
      </Button>
      <Input
        type="text"
        inputmode="numeric"
        value={termStore.settings.fontSize}
        onchange={(e) => {
          termStore.updateSettings({
            fontSize: parseInt(e.currentTarget.value, 10) || 14,
          });
          e.currentTarget.value = String(termStore.settings.fontSize);
        }}
        class="h-8 w-14 text-center"
      />
      <Button
        variant="outline"
        size="icon-sm"
        disabled={termStore.settings.fontSize >= 32}
        onclick={() =>
          termStore.updateSettings({
            fontSize: termStore.settings.fontSize + 1,
          })}
      >
        <Plus class="h-3.5 w-3.5" />
      </Button>
    </div>
  </div>

  <!-- Font Preview -->
  <div class="grid grid-cols-[120px_1fr] items-start gap-3">
    <Label class="pt-2">Preview</Label>
    <div
      class="overflow-hidden rounded-md border"
      style:background-color="var(--terminal-background)"
      style:color="var(--terminal-foreground)"
    >
      <pre
        class="m-0 overflow-hidden p-3 leading-normal"
        style="font-family: {termStore.fontFamily};
                     font-size: {termStore.fontSize}px;"><span
          style="color:var(--terminal-ansi-green)">$</span
        > echo "Hello, World!"
{#each fontPreviewLines as line (line)}{line}
        {/each}</pre>
    </div>
  </div>
</section>

// frontend/src/components/settings-dialog/TerminalSettings.tsx
import { Minus, Plus, Terminal, Type } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useTerminalStore } from "@/lib/stores/terminal";
import { BUNDLED_FONTS } from "@/lib/terminal/fonts";

const settingsRowClass =
  "grid gap-2 sm:grid-cols-[120px_minmax(0,1fr)] sm:items-center sm:gap-3";

export default function TerminalSettings() {
  const settings = useTerminalStore((state) => state.settings);
  const fontFamily = useTerminalStore((state) => state.fontFamily);
  const updateSettings = useTerminalStore((state) => state.updateSettings);

  const fontPreviewLines = [
    "Hello, World!",
    "ABCDEFGHIJKLM 0123456789",
    "abcdefghijklm ~!@#$%^&*()",
  ];

  return (
    <section className="space-y-3">
      <div className="flex items-center gap-2">
        <Terminal className="h-4 w-4 text-muted-foreground" />
        <h3 className="text-sm font-medium">Font</h3>
      </div>
      <div className={settingsRowClass}>
        <Label className="text-xs font-medium text-muted-foreground sm:text-sm">
          Source
        </Label>
        <div className="flex flex-wrap gap-1">
          <Button
            variant={settings.fontSource === "default" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => void updateSettings({ fontSource: "default" })}
          >
            Default
          </Button>
          <Button
            variant={settings.fontSource === "system" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => void updateSettings({ fontSource: "system" })}
          >
            System
          </Button>
          <Button
            variant={settings.fontSource === "bundled" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => void updateSettings({ fontSource: "bundled" })}
          >
            <Type className="mr-1.5 h-3.5 w-3.5" />
            Bundled
          </Button>
        </div>
      </div>

      {settings.fontSource === "system" ? (
        <div className={settingsRowClass}>
          <Label className="text-xs font-medium text-muted-foreground sm:text-sm">
            Font Family
          </Label>
          <Input
            type="text"
            placeholder="'My Font', monospace"
            value={settings.systemFontFamily}
            onChange={(event) =>
              void updateSettings({
                systemFontFamily: event.currentTarget.value,
              })
            }
          />
        </div>
      ) : null}

      {settings.fontSource === "bundled" ? (
        <div className={settingsRowClass}>
          <Label className="text-xs font-medium text-muted-foreground sm:text-sm">
            Bundled Font
          </Label>
          <Select
            value={settings.bundledFont}
            onValueChange={(value) =>
              void updateSettings({ bundledFont: value })
            }
          >
            <SelectTrigger className="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {BUNDLED_FONTS.map((font) => (
                <SelectItem key={font.id} value={font.id}>
                  {font.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      ) : null}

      <div className={settingsRowClass}>
        <Label className="text-xs font-medium text-muted-foreground sm:text-sm">
          Font Size
        </Label>
        <div className="flex flex-wrap items-center gap-1">
          <Button
            variant="outline"
            size="icon-sm"
            disabled={settings.fontSize <= 8}
            onClick={() =>
              void updateSettings({ fontSize: settings.fontSize - 1 })
            }
          >
            <Minus className="h-3.5 w-3.5" />
          </Button>
          <Input
            type="text"
            inputMode="numeric"
            value={String(settings.fontSize)}
            onChange={(event) =>
              void updateSettings({
                fontSize: Number.parseInt(event.currentTarget.value, 10) || 14,
              })
            }
            className="h-8 w-14 text-center"
          />
          <Button
            variant="outline"
            size="icon-sm"
            disabled={settings.fontSize >= 32}
            onClick={() =>
              void updateSettings({ fontSize: settings.fontSize + 1 })
            }
          >
            <Plus className="h-3.5 w-3.5" />
          </Button>
        </div>
      </div>

      <div className="grid gap-2 sm:grid-cols-[120px_minmax(0,1fr)] sm:items-start sm:gap-3">
        <Label className="text-xs font-medium text-muted-foreground sm:pt-2 sm:text-sm">
          Preview
        </Label>
        <div
          className="overflow-hidden rounded-md border"
          style={{
            backgroundColor: "var(--terminal-background)",
            color: "var(--terminal-foreground)",
          }}
        >
          <pre
            className="m-0 overflow-hidden p-3 leading-normal"
            style={{
              fontFamily,
              fontSize: `${settings.fontSize}px`,
            }}
          >
            <span style={{ color: "var(--terminal-ansi-green)" }}>$</span> echo
            "Hello, World!"
            {"\n"}
            {fontPreviewLines.join("\n")}
          </pre>
        </div>
      </div>
    </section>
  );
}
