// frontend-react/src/components/AddProjectDialog.tsx
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { FileBrowser } from "./FileBrowser";

interface AddProjectDialogProps {
  onAdd: (path: string) => Promise<void>;
  onClose: () => void;
}

export function AddProjectDialog({ onAdd, onClose }: AddProjectDialogProps) {
  const [path, setPath] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  async function submit() {
    if (!path.trim()) return;
    setSubmitting(true);
    setError("");
    try {
      await onAdd(path.trim());
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setSubmitting(false);
    }
  }

  function handleSelect(selectedPath: string) {
    setPath(selectedPath);
    // Submit after setting path — use the selected
    // path directly since setState is async.
    (async () => {
      setSubmitting(true);
      setError("");
      try {
        await onAdd(selectedPath.trim());
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setSubmitting(false);
      }
    })();
  }

  return (
    <Dialog
      open
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Add Project</DialogTitle>
          <DialogDescription>
            Browse to a directory or enter a path manually.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-3 py-3">
          <FileBrowser
            currentPath={path}
            onPathChange={setPath}
            onSelect={handleSelect}
          />
          <Separator />
          <div className="flex items-center gap-2">
            <Input
              type="text"
              value={path}
              onChange={(e) => setPath(e.target.value)}
              placeholder="/home/user/repos/myproject"
              disabled={submitting}
              onKeyDown={(e) => {
                if (e.key === "Enter") submit();
              }}
              className="flex-1"
            />
            <Button onClick={submit} disabled={submitting || !path.trim()}>
              Add
            </Button>
          </div>
          {error && <p className="text-sm text-destructive">{error}</p>}
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={submitting}>
            Cancel
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/lib/components/AddProjectDialog.svelte
<script lang="ts">
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Separator } from "$lib/components/ui/separator/index.js";
  import FileBrowser from "./FileBrowser.svelte";

  let {
    onAdd,
    onClose,
  }: {
    onAdd: (path: string) => Promise<void>;
    onClose: () => void;
  } = $props();

  let path = $state("");
  let submitting = $state(false);
  let error = $state("");

  async function submit() {
    if (!path.trim()) return;
    submitting = true;
    error = "";
    try {
      await onAdd(path.trim());
    } catch (e) {
      error = (e as Error).message;
    } finally {
      submitting = false;
    }
  }

  function handleSelect(selectedPath: string) {
    path = selectedPath;
    submit();
  }
</script>

<Dialog.Root
  open
  onOpenChange={(open) => {
    if (!open) onClose();
  }}
>
  <Dialog.Content class="sm:max-w-2xl">
    <Dialog.Header>
      <Dialog.Title>Add Project</Dialog.Title>
      <Dialog.Description>
        Browse to a directory or enter a path manually.
      </Dialog.Description>
    </Dialog.Header>
    <div class="grid gap-3 py-3">
      <FileBrowser bind:currentPath={path} onSelect={handleSelect} />
      <Separator />
      <div class="flex items-center gap-2">
        <Input
          type="text"
          bind:value={path}
          placeholder="/home/user/repos/myproject"
          disabled={submitting}
          onkeydown={(e: KeyboardEvent) => {
            if (e.key === "Enter") submit();
          }}
          class="flex-1"
        />
        <Button onclick={submit} disabled={submitting || !path.trim()}>
          Add
        </Button>
      </div>
      {#if error}
        <p class="text-sm text-destructive">{error}</p>
      {/if}
    </div>
    <Dialog.Footer>
      <Button variant="outline" onclick={onClose} disabled={submitting}>
        Cancel
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
