// frontend/src/components/SidebarResizeHandle.tsx
import { useCallback, useEffect, useRef } from "react";
import { useSidebar } from "@/components/ui/sidebar";
import { useSidebarWidthStore } from "@/lib/stores/sidebarWidth";

const KEYBOARD_RESIZE_STEP = 16;

type ResizeState = {
  pointerId: number;
  startX: number;
  startWidth: number;
};

export default function SidebarResizeHandle() {
  const sidebar = useSidebar();
  const width = useSidebarWidthStore((state) => state.width);
  const isResizing = useSidebarWidthStore((state) => state.isResizing);
  const setWidth = useSidebarWidthStore((state) => state.setWidth);
  const setResizing = useSidebarWidthStore((state) => state.setResizing);
  const flushPendingPersist = useSidebarWidthStore(
    (state) => state.flushPendingPersist,
  );

  const resizeStateRef = useRef<ResizeState | null>(null);
  const pendingClientXRef = useRef<number | null>(null);
  const resizeRafIdRef = useRef<number | null>(null);

  const applyResize = useCallback(
    (clientX: number): void => {
      const resizeState = resizeStateRef.current;
      if (!resizeState) {
        return;
      }
      setWidth(resizeState.startWidth + clientX - resizeState.startX);
    },
    [setWidth],
  );

  const flushQueuedResize = useCallback((): void => {
    resizeRafIdRef.current = null;
    if (pendingClientXRef.current === null) {
      return;
    }
    applyResize(pendingClientXRef.current);
    pendingClientXRef.current = null;
  }, [applyResize]);

  const clearQueuedResize = useCallback((): void => {
    if (resizeRafIdRef.current !== null) {
      cancelAnimationFrame(resizeRafIdRef.current);
    }
    flushQueuedResize();
  }, [flushQueuedResize]);

  function queueResize(clientX: number): void {
    pendingClientXRef.current = clientX;
    if (resizeRafIdRef.current !== null) {
      return;
    }
    resizeRafIdRef.current = requestAnimationFrame(flushQueuedResize);
  }

  useEffect(() => {
    return () => {
      clearQueuedResize();
      setResizing(false);
      flushPendingPersist();
    };
  }, [clearQueuedResize, flushPendingPersist, setResizing]);

  return (
    <button
      type="button"
      aria-label="Resize sidebar"
      className={[
        "fixed inset-y-0 left-[calc(var(--sidebar-width)-4px)] z-30 hidden",
        "w-2 cursor-e-resize touch-none bg-transparent p-0",
        "transition-[left,opacity] duration-200 ease-linear md:block",
        "peer-data-[state=collapsed]:-left-10",
        "peer-data-[state=collapsed]:pointer-events-none",
        "peer-data-[state=collapsed]:opacity-0",
        "after:absolute after:inset-y-0 after:left-1/2 after:w-[2px]",
        "after:-translate-x-1/2 hover:after:bg-sidebar-border",
        "focus-visible:after:bg-sidebar-border",
        isResizing ? "!transition-none" : "",
      ].join(" ")}
      onPointerDown={(event) => {
        if (event.button !== 0 || sidebar.isMobile) {
          return;
        }

        resizeStateRef.current = {
          pointerId: event.pointerId,
          startX: event.clientX,
          startWidth: width,
        };
        setResizing(true);
        event.currentTarget.setPointerCapture(event.pointerId);
        clearQueuedResize();
        event.preventDefault();
      }}
      onPointerMove={(event) => {
        if (resizeStateRef.current?.pointerId !== event.pointerId) {
          return;
        }
        queueResize(event.clientX);
      }}
      onPointerUp={(event) => {
        if (resizeStateRef.current?.pointerId !== event.pointerId) {
          return;
        }
        if (event.currentTarget.hasPointerCapture(event.pointerId)) {
          event.currentTarget.releasePointerCapture(event.pointerId);
        }
        clearQueuedResize();
        applyResize(event.clientX);
        resizeStateRef.current = null;
        setResizing(false);
        flushPendingPersist();
      }}
      onPointerCancel={(event) => {
        if (resizeStateRef.current?.pointerId !== event.pointerId) {
          return;
        }
        clearQueuedResize();
        resizeStateRef.current = null;
        setResizing(false);
        flushPendingPersist();
      }}
      onLostPointerCapture={() => {
        clearQueuedResize();
        resizeStateRef.current = null;
        setResizing(false);
        flushPendingPersist();
      }}
      onKeyDown={(event) => {
        if (sidebar.isMobile) {
          return;
        }

        if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") {
          return;
        }

        event.preventDefault();
        setWidth(
          width +
            (event.key === "ArrowRight"
              ? KEYBOARD_RESIZE_STEP
              : -KEYBOARD_RESIZE_STEP),
        );
      }}
    />
  );
}

// frontend/src/lib/components/SidebarResizeHandle.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { useSidebar } from "$lib/components/ui/sidebar/index.js";
  import { getSidebarWidthStore } from "$lib/stores/sidebarWidth.svelte";

  type ResizeState = {
    pointerId: number;
    startX: number;
    startWidth: number;
  };

  const KEYBOARD_RESIZE_STEP = 16;

  const sidebar = useSidebar();
  const sidebarWidthStore = getSidebarWidthStore();

  let resizeState = $state<ResizeState | null>(null);
  let pendingClientX = $state<number | null>(null);
  let resizeRafId: number | null = null;

  function clearQueuedResize(): void {
    if (resizeRafId != null) {
      cancelAnimationFrame(resizeRafId);
      resizeRafId = null;
    }
    pendingClientX = null;
  }

  function applyResize(clientX: number): void {
    if (!resizeState) {
      return;
    }

    const delta = clientX - resizeState.startX;
    sidebarWidthStore.setWidth(resizeState.startWidth + delta);
  }

  function flushQueuedResize(): void {
    resizeRafId = null;
    if (pendingClientX == null) {
      return;
    }
    applyResize(pendingClientX);
    pendingClientX = null;
  }

  function queueResize(clientX: number): void {
    pendingClientX = clientX;
    if (resizeRafId != null) {
      return;
    }
    resizeRafId = requestAnimationFrame(flushQueuedResize);
  }

  function handlePointerDown(e: PointerEvent): void {
    if (e.button !== 0 || sidebar.isMobile) {
      return;
    }

    resizeState = {
      pointerId: e.pointerId,
      startX: e.clientX,
      startWidth: sidebarWidthStore.width,
    };

    sidebarWidthStore.setResizing(true);

    const handle = e.currentTarget as HTMLElement | null;
    handle?.setPointerCapture(e.pointerId);
    clearQueuedResize();
    e.preventDefault();
  }

  function handlePointerMove(e: PointerEvent): void {
    if (!resizeState || e.pointerId !== resizeState.pointerId) {
      return;
    }

    queueResize(e.clientX);
  }

  function handlePointerEnd(e: PointerEvent): void {
    if (!resizeState || e.pointerId !== resizeState.pointerId) {
      return;
    }

    const handle = e.currentTarget as HTMLElement | null;
    if (handle?.hasPointerCapture(e.pointerId)) {
      handle.releasePointerCapture(e.pointerId);
    }
    clearQueuedResize();
    applyResize(e.clientX);
    resizeState = null;
    sidebarWidthStore.setResizing(false);
    sidebarWidthStore.flushPendingPersist();
  }

  function handleKeydown(e: KeyboardEvent): void {
    if (sidebar.isMobile) {
      return;
    }

    if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") {
      return;
    }

    e.preventDefault();
    const delta =
      e.key === "ArrowRight" ? KEYBOARD_RESIZE_STEP : -KEYBOARD_RESIZE_STEP;
    sidebarWidthStore.setWidth(sidebarWidthStore.width + delta);
  }

  onDestroy(() => {
    clearQueuedResize();
    sidebarWidthStore.setResizing(false);
    sidebarWidthStore.flushPendingPersist();
  });
</script>

<button
  type="button"
  aria-label="Resize sidebar"
  class="fixed inset-y-0 left-[calc(var(--sidebar-width)-4px)]
    z-30 hidden w-2 cursor-e-resize touch-none bg-transparent
    p-0 transition-[left,opacity] duration-200 ease-linear
    md:block
    peer-data-[state=collapsed]:-left-10
    peer-data-[state=collapsed]:pointer-events-none
    peer-data-[state=collapsed]:opacity-0
    after:absolute after:inset-y-0 after:left-1/2
    after:w-[2px] after:-translate-x-1/2
    hover:after:bg-sidebar-border
    focus-visible:after:bg-sidebar-border"
  class:!transition-none={sidebarWidthStore.isResizing}
  onpointerdown={handlePointerDown}
  onpointermove={handlePointerMove}
  onpointerup={handlePointerEnd}
  onpointercancel={handlePointerEnd}
  onlostpointercapture={handlePointerEnd}
  onkeydown={handleKeydown}
></button>
