// frontend/src/components/settings-dialog/ThemeSelect.tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { themeEntries } from "@/lib/stores/theme";

const settingsRowClass =
  "grid gap-2 sm:grid-cols-[120px_minmax(0,1fr)] sm:items-center sm:gap-3";

export default function ThemeSelect({
  label,
  themes,
  value,
  onChange,
}: {
  label: string;
  themes: ReturnType<typeof themeEntries>;
  value: string;
  onChange: (value: string) => void;
}) {
  const selectedName =
    themes.find((theme) => theme.id === value)?.name ?? "Select…";

  return (
    <div className={settingsRowClass}>
      <Label className="text-xs font-medium text-muted-foreground sm:text-sm">
        {label}
      </Label>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger className="w-full">
          <SelectValue placeholder={selectedName} />
        </SelectTrigger>
        <SelectContent>
          {themes.map((theme) => (
            <SelectItem key={theme.id} value={theme.id}>
              {theme.name}
              {theme.builtin ? (
                <span className="ml-1 text-xs text-muted-foreground">
                  Built-in
                </span>
              ) : null}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
}

// frontend/src/lib/components/ThemeSelect.svelte
<script lang="ts">
  import * as Select from "$lib/components/ui/select/index.js";
  import { Label } from "$lib/components/ui/label/index.js";
  import type { ThemeListEntry } from "$lib/theme/types";

  let {
    label,
    themes,
    value,
    onchange,
  }: {
    label: string;
    themes: ThemeListEntry[];
    value: string;
    onchange: (id: string) => void;
  } = $props();

  let selectedName = $derived(
    themes.find((t) => t.id === value)?.name ?? "Select…",
  );
</script>

<div class="grid grid-cols-[120px_1fr] items-center gap-3">
  <Label>{label}</Label>
  <Select.Root
    type="single"
    {value}
    onValueChange={(v: string) => {
      if (v) onchange(v);
    }}
  >
    <Select.Trigger class="w-full">
      <span data-slot="select-value">
        {selectedName}
      </span>
    </Select.Trigger>
    <Select.Content>
      {#each themes as t (t.id)}
        <Select.Item value={t.id} label={t.name}>
          {t.name}
          {#if t.builtin}
            <span class="ml-1 text-xs text-muted-foreground"> Built-in </span>
          {/if}
        </Select.Item>
      {/each}
    </Select.Content>
  </Select.Root>
</div>
