// frontend/src/lib/components/sidebar/SidebarDialogs.svelte
<script lang="ts">
  import AddProjectDialog from "../AddProjectDialog.svelte";
  import AddWorktreeDialog from "../AddWorktreeDialog.svelte";
  import ConfirmDialog from "../ConfirmDialog.svelte";
  import RenameProjectDialog from "../RenameProjectDialog.svelte";
  import SettingsDialog from "../SettingsDialog.svelte";
  import type { Project } from "$lib/types";
  import type {
    ProjectStore,
    SidebarDialogState,
    WorktreeStore,
  } from "./types.js";

  let {
    dialogState,
    projectStore,
    worktreeStore,
  }: {
    dialogState: SidebarDialogState;
    projectStore: ProjectStore;
    worktreeStore: WorktreeStore;
  } = $props();

  async function removeProject(
    projectId: string,
    force = false,
  ): Promise<void> {
    try {
      await projectStore.remove(projectId, force);
      dialogState.actionError = null;
    } catch (err) {
      if (!force && (err as Error).message === "409") {
        dialogState.confirmForceRemoveProject = projectId;
      } else {
        dialogState.actionError = `Failed to remove project (${(err as Error).message})`;
      }
    }
  }

  async function removeWorktree(
    projectId: string,
    worktreeId: string,
    force = false,
  ): Promise<void> {
    try {
      await worktreeStore.remove(projectId, worktreeId, force);
      dialogState.actionError = null;
    } catch (err) {
      const message = (err as Error).message;
      if (!force && message === "409") {
        // Need the worktree object for the force confirm dialog.
        // Look it up from the store since we only have the ID here.
        const wt = worktreeStore
          .worktreesForProject(projectId)
          .find((w) => w.id === worktreeId);
        if (wt) {
          dialogState.confirmForceRemoveWorktree = {
            projectId,
            worktree: wt,
          };
        }
      } else {
        dialogState.actionError = `Failed to delete worktree (${message})`;
      }
    }
  }
</script>

{#if dialogState.addProject}
  <AddProjectDialog
    onAdd={async (path) => {
      await projectStore.add(path);
      dialogState.addProject = false;
    }}
    onClose={() => (dialogState.addProject = false)}
  />
{/if}

{#if dialogState.addWorktree}
  <AddWorktreeDialog
    projectId={dialogState.addWorktree.projectId}
    projectName={dialogState.addWorktree.projectName}
    onAdd={async (branch, startPoint) => {
      await worktreeStore.create(
        dialogState.addWorktree!.projectId,
        branch,
        startPoint,
      );
      dialogState.addWorktree = null;
    }}
    onClose={() => (dialogState.addWorktree = null)}
  />
{/if}

{#if dialogState.renameProject}
  <RenameProjectDialog
    currentName={dialogState.renameProject.currentName}
    onRename={(name) =>
      projectStore.rename(dialogState.renameProject!.projectId, name)}
    onClose={() => (dialogState.renameProject = null)}
  />
{/if}

{#if dialogState.confirmRemoveProject}
  {@const project = projectStore.projects.find(
    (p: Project) => p.id === dialogState.confirmRemoveProject,
  )}
  <ConfirmDialog
    title="Remove Project"
    description="Remove {project?.name ??
      'this project'} and delete all non-local worktrees for it?"
    confirmLabel="Remove"
    onConfirm={() => {
      const id = dialogState.confirmRemoveProject!;
      dialogState.confirmRemoveProject = null;
      void removeProject(id);
    }}
    onClose={() => (dialogState.confirmRemoveProject = null)}
  />
{/if}

{#if dialogState.confirmForceRemoveProject}
  {@const project = projectStore.projects.find(
    (p: Project) => p.id === dialogState.confirmForceRemoveProject,
  )}
  <ConfirmDialog
    title="Force Remove Project"
    description="Project {project?.name ??
      'this project'} has linked worktrees with uncommitted changes or busy state. Force remove it anyway?"
    confirmLabel="Force Remove"
    onConfirm={() => {
      const id = dialogState.confirmForceRemoveProject!;
      dialogState.confirmForceRemoveProject = null;
      void removeProject(id, true);
    }}
    onClose={() => (dialogState.confirmForceRemoveProject = null)}
  />
{/if}

{#if dialogState.confirmRemoveWorktree}
  <ConfirmDialog
    title="Delete Worktree"
    description="Delete worktree {dialogState.confirmRemoveWorktree.worktree
      .name}? This removes the worktree directory from disk."
    confirmLabel="Delete"
    onConfirm={() => {
      const target = dialogState.confirmRemoveWorktree!;
      dialogState.confirmRemoveWorktree = null;
      void removeWorktree(target.projectId, target.worktree.id, false);
    }}
    onClose={() => (dialogState.confirmRemoveWorktree = null)}
  />
{/if}

{#if dialogState.confirmForceRemoveWorktree}
  <ConfirmDialog
    title="Force Delete Worktree"
    description="Worktree {dialogState.confirmForceRemoveWorktree.worktree
      .name} has uncommitted changes or is busy. Force delete it anyway?"
    confirmLabel="Force Delete"
    onConfirm={() => {
      const target = dialogState.confirmForceRemoveWorktree!;
      dialogState.confirmForceRemoveWorktree = null;
      void removeWorktree(target.projectId, target.worktree.id, true);
    }}
    onClose={() => (dialogState.confirmForceRemoveWorktree = null)}
  />
{/if}

<SettingsDialog bind:open={dialogState.showSettings} />

// frontend-react/src/components/app-sidebar/SidebarDialogs.tsx
import AddProjectDialog from "@/components/AddProjectDialog";
import AddWorktreeDialog from "@/components/AddWorktreeDialog";
import ConfirmDialog from "@/components/ConfirmDialog";
import RenameProjectDialog from "@/components/RenameProjectDialog";
import SettingsDialog from "@/components/SettingsDialog";
import type { Project } from "@/lib/types";
import type { DialogState } from "./types";

type SidebarDialogsProps = {
  dialogState: DialogState;
  projects: Project[];
  setDialogState: React.Dispatch<React.SetStateAction<DialogState>>;
  onAddProject: (path: string) => Promise<unknown>;
  onAddWorktree: (
    projectId: string,
    branch: string,
    startPoint?: string,
  ) => Promise<unknown>;
  onRenameProject: (projectId: string, name: string) => Promise<unknown>;
  onRemoveProject: (projectId: string, force?: boolean) => Promise<void>;
  onRemoveWorktree: (
    projectId: string,
    worktreeId: string,
    force?: boolean,
  ) => Promise<void>;
};

export default function SidebarDialogs({
  dialogState,
  projects,
  setDialogState,
  onAddProject,
  onAddWorktree,
  onRenameProject,
  onRemoveProject,
  onRemoveWorktree,
}: SidebarDialogsProps) {
  return (
    <>
      {dialogState.addProject ? (
        <AddProjectDialog
          onAdd={async (path) => {
            await onAddProject(path);
            setDialogState((state) => ({ ...state, addProject: false }));
          }}
          onClose={() =>
            setDialogState((state) => ({ ...state, addProject: false }))
          }
        />
      ) : null}

      {dialogState.addWorktree ? (
        <AddWorktreeDialog
          projectId={dialogState.addWorktree.projectId}
          projectName={dialogState.addWorktree.projectName}
          onAdd={async (branch, startPoint) => {
            await onAddWorktree(
              dialogState.addWorktree!.projectId,
              branch,
              startPoint,
            );
            setDialogState((state) => ({ ...state, addWorktree: null }));
          }}
          onClose={() =>
            setDialogState((state) => ({ ...state, addWorktree: null }))
          }
        />
      ) : null}

      {dialogState.renameProject ? (
        <RenameProjectDialog
          currentName={dialogState.renameProject.currentName}
          onRename={async (name): Promise<void> => {
            await onRenameProject(dialogState.renameProject!.projectId, name);
          }}
          onClose={() =>
            setDialogState((state) => ({ ...state, renameProject: null }))
          }
        />
      ) : null}

      {dialogState.confirmRemoveProject ? (
        <ConfirmDialog
          title="Remove Project"
          description={`Remove ${
            projects.find(
              (project) => project.id === dialogState.confirmRemoveProject,
            )?.name ?? "this project"
          } and delete all non-local worktrees for it?`}
          confirmLabel="Remove"
          onConfirm={() => {
            const projectId = dialogState.confirmRemoveProject!;
            setDialogState((state) => ({
              ...state,
              confirmRemoveProject: null,
            }));
            void onRemoveProject(projectId);
          }}
          onClose={() =>
            setDialogState((state) => ({
              ...state,
              confirmRemoveProject: null,
            }))
          }
        />
      ) : null}

      {dialogState.confirmForceRemoveProject ? (
        <ConfirmDialog
          title="Force Remove Project"
          description={`Project ${
            projects.find(
              (project) => project.id === dialogState.confirmForceRemoveProject,
            )?.name ?? "this project"
          } has linked worktrees with uncommitted changes or busy state. Force remove it anyway?`}
          confirmLabel="Force Remove"
          onConfirm={() => {
            const projectId = dialogState.confirmForceRemoveProject!;
            setDialogState((state) => ({
              ...state,
              confirmForceRemoveProject: null,
            }));
            void onRemoveProject(projectId, true);
          }}
          onClose={() =>
            setDialogState((state) => ({
              ...state,
              confirmForceRemoveProject: null,
            }))
          }
        />
      ) : null}

      {dialogState.confirmRemoveWorktree ? (
        <ConfirmDialog
          title="Delete Worktree"
          description={`Delete worktree ${dialogState.confirmRemoveWorktree.worktree.name}? This removes the worktree directory from disk.`}
          confirmLabel="Delete"
          onConfirm={() => {
            const target = dialogState.confirmRemoveWorktree!;
            setDialogState((state) => ({
              ...state,
              confirmRemoveWorktree: null,
            }));
            void onRemoveWorktree(target.projectId, target.worktree.id);
          }}
          onClose={() =>
            setDialogState((state) => ({
              ...state,
              confirmRemoveWorktree: null,
            }))
          }
        />
      ) : null}

      {dialogState.confirmForceRemoveWorktree ? (
        <ConfirmDialog
          title="Force Delete Worktree"
          description={`Worktree ${dialogState.confirmForceRemoveWorktree.worktree.name} has uncommitted changes or is busy. Force delete it anyway?`}
          confirmLabel="Force Delete"
          onConfirm={() => {
            const target = dialogState.confirmForceRemoveWorktree!;
            setDialogState((state) => ({
              ...state,
              confirmForceRemoveWorktree: null,
            }));
            void onRemoveWorktree(target.projectId, target.worktree.id, true);
          }}
          onClose={() =>
            setDialogState((state) => ({
              ...state,
              confirmForceRemoveWorktree: null,
            }))
          }
        />
      ) : null}

      <SettingsDialog
        open={dialogState.showSettings}
        onOpenChange={(open) =>
          setDialogState((state) => ({
            ...state,
            showSettings: open,
          }))
        }
      />
    </>
  );
}
